<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <link rel="stylesheet"href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- css sheet -->
<style>
     h1{
         margin-top: 100px;
         margin-left: 60px;
     }
     .space1{
          margin: 50px;
     }
     .space2{
          margin: 50px;
     }
     button a{
         list-style-type: none;
         color: white;
     }
 </style>
    <title>TEST</title>
</head>
<body>
<div class="container">
    <h1>WELCOME USER :)</h1>
</div>
<div class="container">
    <div class="row">
    <button type="button" class="btn btn-danger col-6 col-sm-3 space1"><a href="teacher.php">faculty</a></button>
    <button type="button" class="btn btn-success col-6 col-sm-3 space2"><a href="student.php">student</a></button>
    </div>

</div>
</body>
</html>